version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./app/node_modules
    command: sh -c "npm install && node index.js"
    tty: true
    networks:
      - node-network
    depends_on:
      - nginx
      - db
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "3001:3001"
    networks:
      - node-network
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge